apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: ecommerce-microservices-k8s-cart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1004
