apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
        - name: offers
          image: ecommerce-microservices-k8s-offers:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1001
