apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ecommerce-microservices-k8s-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
